# Generated by Django 6.0.1 on 2026-01-25 06:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Hudud nomi')),
                ('is_open', models.BooleanField(default=True, verbose_name='Qabul ochiq')),
                ('warning_message', models.CharField(default='Bu hududda qabul tugagan', max_length=200, verbose_name='Ogohlantirish xabari')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Maktab nomi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='hackathon.region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Maktab',
                'verbose_name_plural': 'Maktablar',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism familiya")),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqam')),
                ('grade', models.CharField(choices=[('7', '7-sinf'), ('8', '8-sinf'), ('9', '9-sinf'), ('10', '10-sinf'), ('11', '11-sinf')], max_length=2, verbose_name='Sinf')),
                ('about', models.TextField(verbose_name="O'zingiz haqingizda")),
                ('device', models.CharField(choices=[('none', "Kompyuter yo'q"), ('pc', 'PC'), ('laptop', 'Laptop')], max_length=10, verbose_name='Jihozingiz')),
                ('english_level', models.CharField(choices=[('bilmayman', 'Bilmayman'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, verbose_name='Ingliz tili darajasi')),
                ('status', models.CharField(choices=[('pending', 'KUTILMOQDA'), ('approved', 'QABUL QILINDI'), ('rejected', 'RAD ETILDI')], default='pending', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hackathon.region', verbose_name='Hudud')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hackathon.school', verbose_name='Maktab')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
