# Generated by Django 6.0.1 on 2026-01-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_reason',
            field=models.TextField(blank=True, null=True, verbose_name='AI Izohi'),
        ),
        migrations.AddField(
            model_name='application',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tahlil vaqti'),
        ),
        migrations.AddField(
            model_name='application',
            name='computer_skill',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kompyuter savodxonligi'),
        ),
        migrations.AddField(
            model_name='application',
            name='decision',
            field=models.CharField(choices=[('pending', 'KUTILMOQDA'), ('accepted', 'QABUL QILINDI'), ('rejected', 'RAD ETILDI')], default='pending', max_length=10, verbose_name='AI Qarori'),
        ),
        migrations.AddField(
            model_name='application',
            name='english_skill',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ingliz tili'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'KUTILMOQDA'), ('accepted', 'QABUL QILINDI'), ('rejected', 'RAD ETILDI')], default='pending', max_length=10, verbose_name='Holat'),
        ),
    ]
