# Generated by Django 6.0.1 on 2026-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_application_ai_reason_application_analyzed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='AI Sifat Bahosi'),
        ),
    ]
