# Generated by Django 6.0.1 on 2026-01-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_application_description_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='device',
            field=models.CharField(choices=[('none', "Kompyuter yo'q"), ('pc', 'Shaxsiy kompyuter'), ('laptop', 'Noutbuk')], max_length=10, verbose_name='Jihozingiz'),
        ),
    ]
