# Generated by Django 6.0.1 on 2026-02-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_alter_application_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name="O'zingiz haqingizda"),
        ),
        migrations.AlterField(
            model_name='application',
            name='device',
            field=models.CharField(blank=True, choices=[('none', "Kompyuter yo'q"), ('pc', 'Shaxsiy kompyuter'), ('laptop', 'Noutbuk')], max_length=10, null=True, verbose_name='Jihozingiz'),
        ),
        migrations.AlterField(
            model_name='application',
            name='english_level',
            field=models.CharField(blank=True, choices=[('bilmayman', 'Bilmayman'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10, null=True, verbose_name='Ingliz tili darajasi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='grade',
            field=models.CharField(blank=True, choices=[('7', '7-sinf'), ('8', '8-sinf'), ('9', '9-sinf'), ('10', '10-sinf'), ('11', '11-sinf')], max_length=2, null=True, verbose_name='Sinf'),
        ),
        migrations.AlterField(
            model_name='application',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.region', verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='application',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hackathon.school', verbose_name='Maktab'),
        ),
    ]
