# Generated by Django 6.0.1 on 2026-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_alter_application_about_alter_application_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='decision',
        ),
        migrations.AddField(
            model_name='application',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'KUTILMOQDA'), ('accepted', 'QABUL QILINDI'), ('rejected', 'RAD ETILDI'), ('needs_review', "QAYTA KO'RIB CHIQISH")], default='pending', max_length=15, verbose_name='AI Qarori'),
        ),
    ]
