# Generated by Django 6.0.1 on 2026-02-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_remove_application_decision_application_ai_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Maktab', 'verbose_name_plural': 'Maktablar'},
        ),
        migrations.AddField(
            model_name='region',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='school',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
    ]
