# Generated by Django 6.0.1 on 2026-02-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_alter_region_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Hudud', 'verbose_name_plural': 'Hududlar'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['region', 'name'], 'verbose_name': 'Maktab', 'verbose_name_plural': 'Maktablar'},
        ),
        migrations.RemoveField(
            model_name='region',
            name='order',
        ),
        migrations.RemoveField(
            model_name='school',
            name='order',
        ),
    ]
