# Generated by Django 6.0.1 on 2026-02-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0009_alter_region_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
