# Generated by Django 6.0.1 on 2026-02-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0010_application_telegram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('claimed_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Band qilingan raqam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
            },
        ),
    ]
