# Generated by Django 6.0.1 on 2026-02-08 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0011_botuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=10, verbose_name='Oldingi holat')),
                ('new_status', models.CharField(max_length=10, verbose_name='Yangi holat')),
                ('action_type', models.CharField(default='bulk_status_update', max_length=50, verbose_name='Amal turi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin foydalanuvchi')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_audits', to='hackathon.application', verbose_name='Ariza')),
            ],
            options={
                'verbose_name': "Holat o'zgarish tarixi",
                'verbose_name_plural': "Holat o'zgarish tarixlari",
                'ordering': ['-timestamp'],
            },
        ),
    ]
