# Generated by Django 6.0.1 on 2026-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0012_applicationstatusaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Foydalanuvchi nomi'),
        ),
    ]
