# Generated by Django 6.0.1 on 2026-02-11 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0013_botuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Savol matni')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTestManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Hackathon test management',
                'verbose_name_plural': 'HACKATHON TEST MANAGEMENT',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hackathon.application',),
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_submitted', models.BooleanField(db_index=True, default=False, verbose_name='Yuborilgan')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('overall_level', models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20, null=True, verbose_name='Umumiy daraja')),
                ('overall_status', models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('weak', 'Weak'), ('average', 'Average'), ('strong', 'Strong'), ('excellent', 'Excellent'), ('ai_pending', 'AI evaluation pending')], max_length=20, null=True, verbose_name='Umumiy test holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to='hackathon.application', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Student test',
                'verbose_name_plural': 'Student tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_answer', models.TextField(blank=True, default='', verbose_name='Yozma javob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='hackathon.question', verbose_name='Savol')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hackathon.studenttest', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Student answer',
                'verbose_name_plural': 'Student answers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AIAnswerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20, verbose_name='Baholash darajasi')),
                ('short_reason', models.CharField(max_length=500, verbose_name='Qisqa izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='hackathon.studentanswer', verbose_name='Javob')),
            ],
            options={
                'verbose_name': 'AI answer evaluation',
                'verbose_name_plural': 'AI answer evaluations',
                'indexes': [models.Index(fields=['score_level'], name='aievaluation_score_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='studenttest',
            index=models.Index(fields=['overall_status'], name='studenttest_status_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttest',
            index=models.Index(fields=['submitted_at'], name='studenttest_submitted_idx'),
        ),
        migrations.AddConstraint(
            model_name='studenttest',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_test_per_student'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['test'], name='studentanswer_test_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='unique_question_per_test'),
        ),
    ]
