# Generated by Django 6.0.1 on 2026-02-11 10:50

import django.db.models.deletion
from django.db import migrations, models


def forward_fill_statuses(apps, schema_editor):
    Application = apps.get_model('hackathon', 'Application')
    StudentTest = apps.get_model('hackathon', 'StudentTest')

    for app in Application.objects.all().iterator():
        if app.status in ('accepted', 'approved'):
            app.overall_status = 'qabul_qilindi'
        elif app.status == 'rejected':
            app.overall_status = 'qabul_qilinmadi'
        else:
            app.overall_status = 'kutilayapti'
        app.save(update_fields=['overall_status'])

    # Migrate previous test outcome semantics if old fields existed.
    passing_statuses = {'average', 'strong', 'excellent'}
    for test in StudentTest.objects.all().iterator():
        old_level = getattr(test, 'overall_level', None)
        old_status = getattr(test, 'overall_status', None)
        if old_level:
            test.ai_sifat_bahosi = old_level
        if old_status in passing_statuses:
            test.ai_holat = 'qabul_qilindi'
        elif old_status == 'ai_pending':
            test.ai_holat = 'kutilayapti'
        else:
            test.ai_holat = 'qabul_qilinmadi'
        test.save(update_fields=['ai_sifat_bahosi', 'ai_holat'])


def backward_fill_statuses(apps, schema_editor):
    # No backward data restoration because old fields are removed later in this migration.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0014_question_applicationtestmanagement_studenttest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionTestControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test_active', models.BooleanField(default=False, verbose_name='Test faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hudud test nazorati',
                'verbose_name_plural': 'Hudud test nazoratlari',
            },
        ),
        migrations.RemoveIndex(
            model_name='studenttest',
            name='studenttest_status_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='overall_status',
            field=models.CharField(choices=[('qabul_qilindi', 'Qabul qilindi'), ('qabul_qilinmadi', 'Qabul qilinmadi'), ('kutilayapti', 'Kutilayapti')], db_index=True, default='kutilayapti', max_length=20, verbose_name='Umumiy holat (admin)'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='ai_holat',
            field=models.CharField(choices=[('qabul_qilindi', 'Qabul qilindi'), ('qabul_qilinmadi', 'Qabul qilinmadi'), ('kutilayapti', 'Kutilayapti')], db_index=True, default='kutilayapti', max_length=20, verbose_name='AI holati'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='ai_sifat_bahosi',
            field=models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], max_length=20, null=True, verbose_name='AI sifat bahosi'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='overall_ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI umumiy xulosa'),
        ),
        migrations.AddIndex(
            model_name='studenttest',
            index=models.Index(fields=['ai_holat'], name='studenttest_ai_holat_idx'),
        ),
        migrations.AddField(
            model_name='regiontestcontrol',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_controls', to='hackathon.region', verbose_name='Hudud'),
        ),
        migrations.RunPython(forward_fill_statuses, backward_fill_statuses),
        migrations.RemoveField(
            model_name='studenttest',
            name='overall_level',
        ),
        migrations.RemoveField(
            model_name='studenttest',
            name='overall_status',
        ),
    ]
